import { ICheckEventData } from "../layers/pages/CheckEvent/types/IEventData";
import { EventType } from "../types/EventType";

export const link = "https://www.google.ru/";
export const photoLink = "https://famt.ru/wp-content/uploads/2019/07/k-chemu-snitsya-vino-obschee-tolkovanie-snovideniya.jpg"
export const photoGallery: string[] = [
  photoLink,
  photoLink,
  photoLink,
  photoLink,
  photoLink,
  photoLink, 
];

export const events: ICheckEventData[] = [
  {
    id: 1,
    title: 'Дегустация вина',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.Degustation,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
  {
    id: 1,
    title: 'Дегустация вина',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.Degustation,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
  {
    id: 1,
    title: 'Дегустация вина',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.Degustation,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
  {
    id: 1,
    title: 'Мастер класс',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.MasterClass,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
  {
    id: 1,
    title: 'Мастер класс',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.MasterClass,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
  {
    id: 1,
    title: 'Дегустация вина',
    description: "Но курс на социально-ориентированный национальный проект создаёт предпосылки для дальнейших направлений развития. Задача организации, в особенности же современная методология разработки играет определяющее значение для вывода текущих активов.",
    address: "ул. Ленина, д.78",
    price: 1500,
    link: link,
    eventType: EventType.Degustation,
    dateFrom: new Date(),
    dateTo: new Date(),
    organizerName: "ООО Очень интересно",
    previewPhotoLink: photoLink,
  },
]